<ul class="control menu">
	<li n:if="$useHomepage" n:class="$homepage->isCurrent ? 'active' : ''" >
		{if $homepage->isCurrent}
		<span class="active"><strong>{$homepage->label}</strong></span>
		{else}
		<a href="{$homepage->url}">{$homepage->label}</a>
		{/if}
	</li>

	{block #menu}
	<li n:foreach="$children as $item" n:class="$item->inPath ? 'active' : ''" >
		{if $item->isCurrent}
                    <span class="active"><strong>{$item->label}</strong></span>
		{else}
                    <a href="{$item->url}">{$item->label}</a>
		{/if}
		
		{if $renderChildren && count($item->getComponents()) > 0}
		<ul>
			{include #menu, children => $item->getComponents()}
		</ul>
		{/if}
	</li>
	{/block}
</ul>
